# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/tommy351/hexo/

# Site
title: WebdriverIO - Selenium 2.0 javascript bindings for nodejs
subtitle: Selenium 2.0 bindings for NodeJS
description: A nodejs bindings implementation for selenium 2.0/webdriver.
author: Christian Bromann
email: mail@christian-bromann.com
language: en-EN

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://webdriver.io
root: /
permalink: :title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: code

# Directory
source_dir: source
public_dir: public

# FB open graph
og:
    image: http://webdriver.io/images/webdriver-robot-with-dots.png
    title: WebdriverIO - Selenium 2.0 bindings for NodeJS
    url:   http://webdriver.io
    description: A nodejs bindings implementation for selenium 2.0/webdriver.
    type:  website

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
highlight:
    enable: true
    line_number: true
    tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 5000
server_ip: 0.0.0.0
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: webdriver.io

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: s3
  bucket: webdriver.io
  concurrency: 30
  region: eu-west-1

wdio:
  builds:
    - apiVersion: v3.0
      webdriverio: v3.0
      wddoc: v0.3.2
    - apiVersion: v3.1
      webdriverio: v3.1
      wddoc: v0.3.2
    - apiVersion: v3.2
      webdriverio: v3.2
      wddoc: v0.3.2
    - apiVersion: v3.3
      webdriverio: v3.3
      wddoc: v0.3.2
    - apiVersion: v3.4
      webdriverio: v3.4
      wddoc: v0.3.2
    - apiVersion: v4.0
      webdriverio: v4.0.9
      wddoc: v0.3.2

marked:
    gfm: true
    pedantic: false
    sanitize: false
    tables: true
    breaks: false
    smartLists: true
    smartypants: true

alias:
    docs.html: "http://webdriver.io/api.html"

sitemap:
    path: sitemap.xml
    post_changefreq: daily
    post_priority: 0.8
